function eventLog = ma_executeSetState(setStateEvent, eventNum)
%ma_executeSetState Summary of this function goes here
%   Detailed explanation goes here
    
    event = setStateEvent;

    eventLog = [event.epoch, ...
                event.rVect(1), event.rVect(2), event.rVect(3), ...
                event.vVect(1), event.vVect(2), event.vVect(3), ...
                event.centralBody.id, ...
                event.dryMass, event.fuelOxMass, event.monoMass, event.xenonMass, ...
                eventNum];
end

