function exclude = getLvdGAExcludeList()
    exclude = {};
    exclude{end+1} = 'Distance to Ref. Spacecraft';
    exclude{end+1} = 'Distance to Ref. Station';
    exclude{end+1} = 'Relative Vel. to Ref. Spacecraft';
    exclude{end+1} = 'Relative Pos. of Ref. Spacecraft (In-Track)';
    exclude{end+1} = 'Relative Pos. of Ref. Spacecraft (Cross-Track)';
    exclude{end+1} = 'Relative Pos. of Ref. Spacecraft (Radial)';
    exclude{end+1} = 'Relative Pos. of Ref. Spacecraft (In-Track; Ref. SC-centered)';
    exclude{end+1} = 'Relative Pos. of Ref. Spacecraft (Cross-Track; Ref. SC-centered)';
    exclude{end+1} = 'Relative Pos. of Ref. Spacecraft (Radial; Ref. SC-centered)';
    exclude{end+1} = 'Relative SMA of Ref. Spacecraft';
    exclude{end+1} = 'Relative Eccentricity of Ref. Spacecraft';
    exclude{end+1} = 'Relative Inclination of Ref. Spacecraft';
    exclude{end+1} = 'Relative RAAN of Ref. Spacecraft';
    exclude{end+1} = 'Relative Argument of Periapsis of Ref. Spacecraft';
    exclude{end+1} = 'Elevation Angle w.r.t. Ref. Station';
    exclude{end+1} = 'Line of Sight to Ref. Spacecraft';
    exclude{end+1} = 'Line of Sight to Ref. Station';
    exclude{end+1} = 'Sun-centric Position (X)';
    exclude{end+1} = 'Sun-centric Position (Y)';
    exclude{end+1} = 'Sun-centric Position (Z)';
end