classdef lvd_editAdamNlOptOptionsGUI_App < matlab.apps.AppBase
    %lvd_editAdamNlOptOptionsGUI_App Options editor for the AdamNLOpt optimizer.
    %   Programmatic App Designer (uifigure) window that mirrors the look and
    %   feel of lvd_editFminconOptionsGUI_App.  It is launched exactly like the
    %   other optimizer options editors:
    %
    %       output = AppDesignerGUIOutput({false});
    %       lvd_editAdamNlOptOptionsGUI_App(optimizer, output);
    %
    %   The AdamNlOptOptions object is a handle (matlab.mixin.SetGet), so this
    %   editor mutates it in place; the optimizer sees the changes on Save.
    %
    %   The window is fully resizable (nested uigridlayouts everywhere) and
    %   theme-compatible: it subclasses matlab.apps.AppBase, every themed
    %   component is a public property, and startupFcn calls
    %   applySelectedThemeToApp(app).  NOTE: the AppThemer cannot recolor
    %   TabGroup/Tab backgrounds, so the tab strip keeps its default color; the
    %   panels and controls inside the tabs are themed normally.

    % Framework components
    properties (Access = public)
        UIFigure
        MainGrid
        TitleLabel
        TabGroup
        SaveCloseButton
    end

    % Tabs and their two-column layouts
    properties (Access = public)
        GeneralTab
        GeneralTabGrid
        HessianTab
        HessianTabGrid
        ScalingTab
        ScalingTabGrid
        BarrierTab
        BarrierTabGrid
        DualsTab
        DualsTabGrid
        GuidanceTab
        GuidanceTabGrid
        GuidanceText
    end

    % Group panels and their inner grids
    properties (Access = public)
        TolPanel
        TolGrid
        ObjPlatPanel
        ObjPlatGrid
        FinDiffPanel
        FinDiffGrid
        LimitsPanel
        LimitsGrid
        DiagPanel
        DiagGrid
        ParallelPanel
        ParallelGrid
        HessPanel
        HessGrid
        LinAlgPanel
        LinAlgGrid
        ScalingPanel
        ScalingGrid
        DivergePanel
        DivergeGrid
        GlobPanel
        GlobGrid
        BarrierPanel
        BarrierGrid
        TrustRegPanel
        TrustRegGrid
        AdaptivePanel
        AdaptiveGrid
        DualPanel
        DualGrid
        DegenPanel
        DegenGrid
        BroydenPanel
        BroydenGrid
    end

    % Option controls (property name == AdamNlOptOptions property name)
    properties (Access = public)
        optTol
        feasTol
        compTol
        stepTol
        objPlateauWindow
        objPlateauFtol
        objPlateauOptTol
        objPlateauOptWindow
        finDiffType
        finDiffStepSize
        autoFDStep
        honorBounds
        maxIter
        maxFunEvals
        maxTime
        traceLevel
        traceMaxRows
        warnOnSilentFailure
        plotSolverProgress
        displayMode
        logFile
        parallel
        numWorkers
        hessianApprox
        bfgsGammaCurvCap
        bfgsB0Refresh
        bfgsB0RefreshWindow
        bfgsB0RefreshFactor
        bfgsB0RefreshRefractory
        bfgsB0RefreshMaxDrop
        bfgsB0RefreshMinLearned
        bfgsResetMaxDrop
        bfgsCondMax
        lbfgsMemory
        linearSolver
        krylovMethod
        krylovAutoDim
        krylovMaxIter
        forcingEtaMax
        forcingEtaMin
        forcingGamma
        forcingAlpha
        precondition
        autoScale
        autoScaleMaxSpread
        autoScaleCurvGate
        autoScaleCurvProbeMaxDim
        divergeFactor
        divergeWindow
        returnIterate
        globalization
        kappaThetaGrow
        useSOC
        socMax
        socThreshold
        mu0
        muMin
        muGamma
        muBeta
        kappaMu
        tau
        barrierStallFactor
        feasAdmitFactor
        delta0
        deltaMax
        trEta1
        trEta2
        trShrink
        trExpand
        trMaxInner
        modeSwitch
        modeSwitchStagnWindow
        enableRestoration
        restStallWindow
        modeNearBdryAugJE
        useNTdecomp
        dualStepMax
        dualCondMax
        dualCondProbeMaxDim
        lsMultiplierRefresh
        lsRefreshDomRatio
        lsRefreshFeasTol
        lsRefreshDeadband
        dualFitCondMax
        dualFitCondMinEq
        dualFitGrowthMax
        activeBoundGapTol
        excludeActiveBoundRows
        enableDegeneracyDetection
        enableBroyden
        broydenMaxStale
        broydenTol
        costThreshold
    end

    % Row labels for every non-checkbox control (<name>Lbl)
    properties (Access = public)
        optTolLbl
        feasTolLbl
        compTolLbl
        stepTolLbl
        objPlateauWindowLbl
        objPlateauFtolLbl
        objPlateauOptTolLbl
        objPlateauOptWindowLbl
        finDiffTypeLbl
        finDiffStepSizeLbl
        maxIterLbl
        maxFunEvalsLbl
        maxTimeLbl
        traceLevelLbl
        traceMaxRowsLbl
        displayModeLbl
        logFileLbl
        parallelLbl
        numWorkersLbl
        hessianApproxLbl
        bfgsGammaCurvCapLbl
        bfgsB0RefreshWindowLbl
        bfgsB0RefreshFactorLbl
        bfgsB0RefreshRefractoryLbl
        bfgsB0RefreshMaxDropLbl
        bfgsB0RefreshMinLearnedLbl
        bfgsResetMaxDropLbl
        bfgsCondMaxLbl
        lbfgsMemoryLbl
        linearSolverLbl
        krylovMethodLbl
        krylovAutoDimLbl
        krylovMaxIterLbl
        forcingEtaMaxLbl
        forcingEtaMinLbl
        forcingGammaLbl
        forcingAlphaLbl
        preconditionLbl
        autoScaleLbl
        autoScaleMaxSpreadLbl
        autoScaleCurvGateLbl
        autoScaleCurvProbeMaxDimLbl
        divergeFactorLbl
        divergeWindowLbl
        returnIterateLbl
        globalizationLbl
        kappaThetaGrowLbl
        socMaxLbl
        socThresholdLbl
        mu0Lbl
        muMinLbl
        muGammaLbl
        muBetaLbl
        kappaMuLbl
        tauLbl
        barrierStallFactorLbl
        feasAdmitFactorLbl
        delta0Lbl
        deltaMaxLbl
        trEta1Lbl
        trEta2Lbl
        trShrinkLbl
        trExpandLbl
        trMaxInnerLbl
        modeSwitchStagnWindowLbl
        restStallWindowLbl
        dualStepMaxLbl
        dualCondMaxLbl
        dualCondProbeMaxDimLbl
        lsRefreshDomRatioLbl
        lsRefreshFeasTolLbl
        lsRefreshDeadbandLbl
        dualFitCondMaxLbl
        dualFitCondMinEqLbl
        dualFitGrowthMaxLbl
        activeBoundGapTolLbl
        broydenMaxStaleLbl
        broydenTolLbl
        costThresholdLbl
    end

    % App data (private; not iterated by the themer)
    properties (Access = private)
        Optimizer
        Options
        Output
        Fields  % struct array describing every option field, for load/save/validate
    end

    methods (Access = public)
        function app = lvd_editAdamNlOptOptionsGUI_App(varargin)
            createComponents(app);
            registerApp(app, app.UIFigure);
            runStartupFcn(app, @(app)startupFcn(app, varargin{:}));

            if nargout == 0
                clear app
            end
        end

        function delete(app)
            delete(app.UIFigure);
        end
    end

    methods (Access = private)
        function startupFcn(app, optimizer, output)
            app.Optimizer = optimizer;
            app.Output = output;
            app.Options = optimizer.getOptions();

            centerUIFigure(app.UIFigure);
            applySelectedThemeToApp(app);

            populateGUI(app);
            applyTooltips(app);

            app.UIFigure.Visible = 'on';
            uiwait(app.UIFigure);
        end

        function createComponents(app)
            app.Fields = struct('name', {}, 'label', {}, 'kind', {}, ...
                                'enumClass', {}, 'lb', {}, 'ub', {}, 'isInt', {});

            app.UIFigure = uifigure('Visible', 'off');
            app.UIFigure.Position = [100 100 760 660];
            app.UIFigure.Name = 'Edit AdamNLOpt Options';
            app.UIFigure.WindowStyle = 'modal';

            app.MainGrid = uigridlayout(app.UIFigure, [4 1]);
            app.MainGrid.RowHeight = {28, '1x', 'fit', 34};
            app.MainGrid.ColumnWidth = {'1x'};

            app.TitleLabel = uilabel(app.MainGrid);
            app.TitleLabel.Text = 'Edit AdamNLOpt Options';
            app.TitleLabel.HorizontalAlignment = 'center';
            app.TitleLabel.FontSize = 16;
            app.TitleLabel.FontWeight = 'bold';
            app.TitleLabel.Layout.Row = 1;
            app.TitleLabel.Layout.Column = 1;

            app.TabGroup = uitabgroup(app.MainGrid);
            app.TabGroup.Layout.Row = 2;
            app.TabGroup.Layout.Column = 1;

            % Footer note is intentionally NOT a stored property so the themer
            % leaves its accent color alone (matches the FMINCON editor note).
            noteLbl = uilabel(app.MainGrid);
            noteLbl.Text = 'Leave a text field blank to use that setting''s default value.';
            noteLbl.HorizontalAlignment = 'center';
            noteLbl.FontAngle = 'italic';
            noteLbl.FontColor = [0.85 0.20 0.20];
            noteLbl.Layout.Row = 3;
            noteLbl.Layout.Column = 1;

            app.SaveCloseButton = uibutton(app.MainGrid, 'push');
            app.SaveCloseButton.Text = 'Save & Close';
            app.SaveCloseButton.Icon = 'save-file.png';
            app.SaveCloseButton.ButtonPushedFcn = @(~,~) onSaveClose(app);
            app.SaveCloseButton.Layout.Row = 4;
            app.SaveCloseButton.Layout.Column = 1;

            buildTabs(app);
        end

        function buildTabs(app)
            % Tab 1: General
            tolRows = { ...
                {'optTol','Optimality Tol.','num',[0 Inf 0]}, ...
                {'feasTol','Feasibility Tol.','num',[0 Inf 0]}, ...
                {'compTol','Complementarity Tol.','num',[0 Inf 0]}, ...
                {'stepTol','Step Tol.','num',[0 Inf 0]}};
            objPlatRows = { ...
                {'objPlateauWindow','Plateau Window','num',[1 Inf 1]}, ...
                {'objPlateauFtol','Plateau f Tol.','num',[0 Inf 0]}, ...
                {'objPlateauOptTol','Plateau Opt. Tol.','num',[0 Inf 0]}, ...
                {'objPlateauOptWindow','Plateau Opt. Window','num',[1 Inf 1]}};
            finDiffRows = { ...
                {'finDiffType','FD Type','enum','FminconFiniteDiffTypeEnum'}, ...
                {'finDiffStepSize','FD Step Size','num',[0 Inf 0]}, ...
                {'autoFDStep','Auto-Calibrate FD Step','check',[]}, ...
                {'honorBounds','Honor Bounds','check',[]}};
            limitsRows = { ...
                {'maxIter','Max Iterations','num',[1 Inf 1]}, ...
                {'maxFunEvals','Max Function Evals','num',[1 Inf 1]}, ...
                {'maxTime','Max Time (s)','num',[0 Inf 0]}};
            diagRows = { ...
                {'traceLevel','Trace Level (0-2)','num',[0 2 1]}, ...
                {'traceMaxRows','Trace Max Rows','num',[1 Inf 1]}, ...
                {'displayMode','Console Display','enum','AdamNlOptDisplayEnum'}, ...
                {'logFile','Log File Path','char',[]}, ...
                {'warnOnSilentFailure','Warn On Silent Failure','check',[]}, ...
                {'plotSolverProgress','Plot Solver Progress','check',[]}};
            parallelRows = { ...
                {'parallel','Parallel Mode','enum','AdamNlOptParallelEnum'}, ...
                {'numWorkers','Num. Parallel Workers','num',[1 Inf 1]}};

            app.GeneralTab = uitab(app.TabGroup, 'Title', 'General');
            app.GeneralTabGrid = makeTabGrid(app, app.GeneralTab, 3);
            createPanel(app, app.GeneralTabGrid, 1, 1, 'Tol', 'Tolerances', tolRows);
            createPanel(app, app.GeneralTabGrid, 2, 1, 'ObjPlat', 'Objective Plateau Exit', objPlatRows);
            createPanel(app, app.GeneralTabGrid, 3, 1, 'FinDiff', 'Finite Differences', finDiffRows);
            createPanel(app, app.GeneralTabGrid, 1, 2, 'Limits', 'Maximums (Termination)', limitsRows);
            createPanel(app, app.GeneralTabGrid, 2, 2, 'Diag', 'Diagnostics & Display', diagRows);
            createPanel(app, app.GeneralTabGrid, 3, 2, 'Parallel', 'Parallelization', parallelRows);

            % Tab 2: Hessian & Linear Algebra
            hessRows = { ...
                {'hessianApprox','Hessian Approx.','enum','AdamNlOptHessianApproxEnum'}, ...
                {'bfgsGammaCurvCap','BFGS Curv. Cap','num',[0 Inf 0]}, ...
                {'bfgsB0Refresh','BFGS B0 Refresh','check',[]}, ...
                {'bfgsB0RefreshWindow','B0 Refresh Window','num',[1 Inf 1]}, ...
                {'bfgsB0RefreshFactor','B0 Refresh Factor','num',[0 Inf 0]}, ...
                {'bfgsB0RefreshRefractory','B0 Refresh Refractory','num',[0 Inf 1]}, ...
                {'bfgsB0RefreshMaxDrop','B0 Refresh Max Drop','num',[0 Inf 0]}, ...
                {'bfgsB0RefreshMinLearned','B0 Refresh Min Learned','num',[0 1 0]}, ...
                {'bfgsResetMaxDrop','BFGS Reset Max Drop','num',[0 Inf 0]}, ...
                {'bfgsCondMax','BFGS Cond. Max','num',[0 Inf 0]}, ...
                {'lbfgsMemory','L-BFGS Memory','num',[1 Inf 1]}};
            linAlgRows = { ...
                {'linearSolver','Linear Solver','enum','AdamNlOptLinearSolverEnum'}, ...
                {'krylovMethod','Krylov Method','enum','AdamNlOptKrylovMethodEnum'}, ...
                {'krylovAutoDim','Krylov Auto Dim.','num',[1 Inf 1]}, ...
                {'krylovMaxIter','Krylov Max Iter','num',[1 Inf 1]}, ...
                {'forcingEtaMax','Forcing Eta Max','num',[0 1 0]}, ...
                {'forcingEtaMin','Forcing Eta Min','num',[0 1 0]}, ...
                {'forcingGamma','Forcing Gamma','num',[0 Inf 0]}, ...
                {'forcingAlpha','Forcing Alpha','num',[1 2 0]}, ...
                {'precondition','Preconditioner','enum','AdamNlOptPrecondEnum'}};

            app.HessianTab = uitab(app.TabGroup, 'Title', 'Hessian & Linear Algebra');
            app.HessianTabGrid = makeTabGrid(app, app.HessianTab, 1);
            createPanel(app, app.HessianTabGrid, 1, 1, 'Hess', 'Hessian Model', hessRows);
            createPanel(app, app.HessianTabGrid, 1, 2, 'LinAlg', 'Linear Algebra', linAlgRows);

            % Tab 3: Scaling & Globalization
            scalingRows = { ...
                {'autoScale','Auto Scale Mode','enum','AdamNlOptAutoScaleEnum'}, ...
                {'autoScaleMaxSpread','Max Scale Spread','num',[1 Inf 0]}, ...
                {'autoScaleCurvGate','Curv. Gate','num',[0 Inf 0]}, ...
                {'autoScaleCurvProbeMaxDim','Curv. Probe Max Dim.','num',[1 Inf 1]}};
            divergeRows = { ...
                {'divergeFactor','Divergence Factor','num',[1 Inf 0]}, ...
                {'divergeWindow','Divergence Window','num',[1 Inf 0]}, ...
                {'returnIterate','Return Iterate','enum','AdamNlOptReturnIterateEnum'}};
            globRows = { ...
                {'globalization','Globalization','enum','AdamNlOptGlobalizationEnum'}, ...
                {'kappaThetaGrow','Kappa Theta Grow','num',[0 Inf 0]}, ...
                {'useSOC','Use Second-Order Correction','check',[]}, ...
                {'socMax','SOC Max Re-solves','num',[0 Inf 1]}, ...
                {'socThreshold','SOC Threshold','num',[0 1 0]}};

            app.ScalingTab = uitab(app.TabGroup, 'Title', 'Scaling & Globalization');
            app.ScalingTabGrid = makeTabGrid(app, app.ScalingTab, 2);
            createPanel(app, app.ScalingTabGrid, 1, 1, 'Scaling', 'Automatic Scaling', scalingRows);
            createPanel(app, app.ScalingTabGrid, 2, 1, 'Diverge', 'Divergence & Result', divergeRows);
            createPanel(app, app.ScalingTabGrid, 1, 2, 'Glob', 'Globalization', globRows);

            % Tab 4: Barrier & Trust Region
            barrierRows = { ...
                {'mu0','Initial Barrier (mu0)','num',[0 Inf 0]}, ...
                {'muMin','Min Barrier (muMin)','num',[0 Inf 0]}, ...
                {'muGamma','Barrier Reduction (gamma)','num',[0 1 0]}, ...
                {'muBeta','Barrier Exponent (beta)','num',[0 Inf 0]}, ...
                {'kappaMu','Kappa mu','num',[0 Inf 0]}, ...
                {'tau','Fraction-to-Boundary (tau)','num',[0 1 0]}, ...
                {'barrierStallFactor','Barrier Stall Factor','num',[0 Inf 0]}, ...
                {'feasAdmitFactor','Feas. Admit Factor','num',[0 Inf 0]}};
            trustRegRows = { ...
                {'delta0','Initial TR Radius','num',[0 Inf 0]}, ...
                {'deltaMax','Max TR Radius','num',[0 Inf 0]}, ...
                {'trEta1','TR Accept Ratio (eta1)','num',[0 1 0]}, ...
                {'trEta2','TR Expand Ratio (eta2)','num',[0 1 0]}, ...
                {'trShrink','TR Shrink Factor','num',[0 1 0]}, ...
                {'trExpand','TR Expand Factor','num',[1 Inf 0]}, ...
                {'trMaxInner','TR Max Inner Iters','num',[1 Inf 1]}};
            adaptiveRows = { ...
                {'modeSwitch','Adaptive Mode Switch','check',[]}, ...
                {'modeSwitchStagnWindow','Mode Stagnation Window','num',[1 Inf 1]}, ...
                {'enableRestoration','Enable Restoration','check',[]}, ...
                {'restStallWindow','Restoration Stall Window','num',[1 Inf 1]}, ...
                {'modeNearBdryAugJE','Near-Bdry Augment Eqs.','check',[]}, ...
                {'useNTdecomp','Normal/Tangential Decomp.','check',[]}};

            app.BarrierTab = uitab(app.TabGroup, 'Title', 'Barrier & Trust Region');
            app.BarrierTabGrid = makeTabGrid(app, app.BarrierTab, 2);
            createPanel(app, app.BarrierTabGrid, 1, 1, 'Barrier', 'Barrier', barrierRows);
            createPanel(app, app.BarrierTabGrid, 1, 2, 'TrustReg', 'Trust Region', trustRegRows);
            createPanel(app, app.BarrierTabGrid, 2, 2, 'Adaptive', 'Adaptive Mode & Restoration', adaptiveRows);

            % Tab 5: Duals & Advanced
            dualRows = { ...
                {'dualStepMax','Dual Step Max','num',[0 Inf 0]}, ...
                {'dualCondMax','Dual Cond. Max','num',[0 Inf 0]}, ...
                {'dualCondProbeMaxDim','Dual Cond. Probe Max Dim.','num',[1 Inf 1]}, ...
                {'lsMultiplierRefresh','LS Multiplier Refresh','check',[]}, ...
                {'lsRefreshDomRatio','LS Refresh Dom. Ratio','num',[0 Inf 0]}, ...
                {'lsRefreshFeasTol','LS Refresh Feas. Tol.','num',[0 Inf 0]}, ...
                {'lsRefreshDeadband','LS Refresh Deadband','num',[0 1 0]}, ...
                {'dualFitCondMax','Dual Fit Cond. Max','num',[0 Inf 0]}, ...
                {'dualFitCondMinEq','Dual Fit Min Eqs.','num',[0 Inf 1]}, ...
                {'dualFitGrowthMax','Dual Fit Growth Max','num',[0 Inf 0]}, ...
                {'activeBoundGapTol','Active Bound Gap Tol.','num',[0 Inf 0]}, ...
                {'excludeActiveBoundRows','Exclude Active Bound Rows','check',[]}};
            degenRows = { ...
                {'enableDegeneracyDetection','Enable Degeneracy Detection','check',[]}};
            broydenRows = { ...
                {'enableBroyden','Enable Broyden Updates','check',[]}, ...
                {'broydenMaxStale','Broyden Max Stale','num',[1 Inf 1]}, ...
                {'broydenTol','Broyden Tol.','num',[0 Inf 0]}, ...
                {'costThreshold','Cost Threshold (s)','num',[0 Inf 0]}};

            app.DualsTab = uitab(app.TabGroup, 'Title', 'Duals & Advanced');
            app.DualsTabGrid = makeTabGrid(app, app.DualsTab, 2);
            createPanel(app, app.DualsTabGrid, 1, 1, 'Dual', 'Dual (Lagrange Multiplier) Handling', dualRows);
            createPanel(app, app.DualsTabGrid, 1, 2, 'Degen', 'Degeneracy', degenRows);
            createPanel(app, app.DualsTabGrid, 2, 2, 'Broyden', 'Broyden Jacobian Updating', broydenRows);

            % Tab 6: Guidance (read-only troubleshooting playbook)
            buildGuidanceTab(app);
        end

        function buildGuidanceTab(app)
            %buildGuidanceTab A read-only tab with an ordered "if the solve
            %   misbehaves, try this" playbook.  Rendered as a single HTML
            %   uilabel so it themes with the rest of the app (the AppThemer
            %   sets the label FontColor, which HTML text without its own color
            %   tags inherits) and scrolls inside a fit-height grid.
            app.GuidanceTab = uitab(app.TabGroup, 'Title', 'Guidance');

            g = uigridlayout(app.GuidanceTab, [1 1]);
            g.ColumnWidth = {'1x'};
            g.RowHeight = {'fit'};
            g.Padding = [10 10 10 10];
            g.Scrollable = 'on';
            app.GuidanceTabGrid = g;

            lbl = uilabel(g);
            lbl.Interpreter = 'html';
            lbl.WordWrap = 'on';
            lbl.VerticalAlignment = 'top';
            lbl.Text = getGuidanceText(app);
            lbl.Layout.Row = 1;
            lbl.Layout.Column = 1;
            app.GuidanceText = lbl;
        end

        function g = makeTabGrid(~, parentTab, nRows)
            g = uigridlayout(parentTab, [nRows 2]);
            g.ColumnWidth = {'1x', '1x'};
            g.RowHeight = repmat({'fit'}, 1, nRows);
            g.Padding = [8 8 8 8];
            g.RowSpacing = 6;
            g.ColumnSpacing = 8;
            g.Scrollable = 'on';
        end

        function createPanel(app, tabGrid, rowInCol, colIdx, panelKey, titleText, rows)
            p = uipanel(tabGrid, 'Title', titleText);
            p.FontWeight = 'bold';
            p.Layout.Row = rowInCol;
            p.Layout.Column = colIdx;
            app.([panelKey 'Panel']) = p;

            nRows = numel(rows);
            g = uigridlayout(p, [nRows 2]);
            g.ColumnWidth = {'fit', '1x'};
            g.RowHeight = repmat({'fit'}, 1, nRows);
            g.Padding = [8 8 8 8];
            g.RowSpacing = 4;
            g.ColumnSpacing = 6;
            app.([panelKey 'Grid']) = g;

            for i = 1:nRows
                createRow(app, g, i, rows{i});
            end
        end

        function createRow(app, panelGrid, rowIdx, rowSpec)
            name = rowSpec{1};
            labelText = rowSpec{2};
            kind = rowSpec{3};
            aux = rowSpec{4};

            switch kind
                case 'check'
                    cb = uicheckbox(panelGrid);
                    cb.Text = labelText;
                    cb.Layout.Row = rowIdx;
                    cb.Layout.Column = [1 2];
                    app.(name) = cb;

                otherwise
                    lbl = uilabel(panelGrid);
                    lbl.Text = [labelText '  '];
                    lbl.HorizontalAlignment = 'right';
                    lbl.Layout.Row = rowIdx;
                    lbl.Layout.Column = 1;
                    app.([name 'Lbl']) = lbl;

                    switch kind
                        case {'num', 'char'}
                            ctrl = uieditfield(panelGrid, 'text');
                        case 'enum'
                            ctrl = uidropdown(panelGrid);
                            m = enumeration(aux);
                            [~, I] = sort({m.name});
                            m = m(I);
                            ctrl.Items = {m.name};
                            ctrl.ItemsData = m;
                    end
                    ctrl.Layout.Row = rowIdx;
                    ctrl.Layout.Column = 2;
                    app.(name) = ctrl;
            end

            rec = struct('name', name, 'label', labelText, 'kind', kind, ...
                         'enumClass', '', 'lb', -Inf, 'ub', Inf, 'isInt', false);
            if strcmp(kind, 'enum')
                rec.enumClass = aux;
            elseif strcmp(kind, 'num') && not(isempty(aux))
                rec.lb = aux(1);
                rec.ub = aux(2);
                rec.isInt = logical(aux(3));
            end
            app.Fields(end+1) = rec;
        end

        function populateGUI(app)
            for i = 1:numel(app.Fields)
                f = app.Fields(i);
                switch f.kind
                    case 'num'
                        app.(f.name).Value = numToStr(app, app.Options.(f.name));
                    case 'char'
                        app.(f.name).Value = app.Options.(f.name);
                    case 'check'
                        app.(f.name).Value = app.Options.(f.name);
                    case 'enum'
                        app.(f.name).Value = app.Options.(f.name);
                end
            end
        end

        function applyTooltips(app)
            % Build a mouse-over tooltip for every control: a detailed
            % description of what the option does, practical guidance on when
            % to change it / what to set it to, and its default value.  Each
            % entry in getOptionDescriptions is a struct with a 'desc' field
            % (what it does) and a 'use' field (when-to-use guidance; may be
            % empty for options that need no extra guidance).
            desc     = getOptionDescriptions(app);
            defaults = AdamNlOptOptions();   % a fresh object holds the defaults

            for i = 1:numel(app.Fields)
                f = app.Fields(i);
                if isfield(desc, f.name)
                    dtxt = desc.(f.name).desc;
                    utxt = desc.(f.name).use;
                else
                    dtxt = f.label;
                    utxt = '';
                end
                defStr = formatDefault(app, f, defaults.(f.name));

                if isempty(utxt)
                    tip = sprintf('%s\n\nDefault: %s', dtxt, defStr);
                else
                    tip = sprintf('%s\n\nWhen to use: %s\n\nDefault: %s', ...
                                  dtxt, utxt, defStr);
                end

                app.(f.name).Tooltip = tip;
                if isprop(app, [f.name 'Lbl']) && not(isempty(app.([f.name 'Lbl'])))
                    app.([f.name 'Lbl']).Tooltip = tip;
                end
            end
        end

        function s = formatDefault(app, f, v)
            switch f.kind
                case 'check'
                    if v, s = 'true'; else, s = 'false'; end
                case 'enum'
                    s = char(v.name);
                case 'char'
                    if isempty(v), s = '(none)'; else, s = char(v); end
                otherwise   % num
                    if isnan(v)
                        s = 'automatic (set by the solver)';
                    else
                        s = numToStr(app, v);
                        if isempty(s), s = 'automatic (set by the solver)'; end
                    end
            end
        end

        function [ok, errMsg] = validateGUI(app)
            errMsg = {};
            for i = 1:numel(app.Fields)
                f = app.Fields(i);
                if strcmp(f.kind, 'num')
                    enteredStr = strtrim(app.(f.name).Value);
                    if not(isempty(enteredStr))
                        value = str2double(enteredStr);
                        errMsg = validateNumber(value, f.label, f.lb, f.ub, ...
                                                f.isInt, errMsg, enteredStr);
                    end
                end
            end
            ok = isempty(errMsg);
        end

        function writeGUIToOptions(app)
            for i = 1:numel(app.Fields)
                f = app.Fields(i);
                switch f.kind
                    case 'num'
                        app.Options.(f.name) = strToNum(app, app.(f.name).Value);
                    case 'char'
                        app.Options.(f.name) = char(app.(f.name).Value);
                    case 'check'
                        app.Options.(f.name) = app.(f.name).Value;
                    case 'enum'
                        app.Options.(f.name) = app.(f.name).Value;
                end
            end
        end

        function onSaveClose(app)
            [ok, errMsg] = validateGUI(app);
            if not(ok)
                uialert(app.UIFigure, strjoin(errMsg, newline), 'Invalid Options');
                return;
            end

            writeGUIToOptions(app);
            app.Output.output = {true};
            delete(app.UIFigure);
        end

        function s = numToStr(~, v)
            if isnan(v)
                s = '';
            elseif isinf(v)
                s = num2str(v);
            else
                s = fullAccNum2Str(v);
            end
        end

        function v = strToNum(~, value)
            s = strtrim(value);
            if isempty(s)
                v = NaN;
            else
                v = str2double(s);
            end
        end

        function txt = getGuidanceText(~)
            %getGuidanceText HTML body for the Guidance tab: an ordered
            %   "if the optimizer isn't working well, try this" playbook.  Each
            %   step names the exact tab > panel > field to change.  No colors
            %   are set in the markup so the text inherits the themed label
            %   FontColor (see buildGuidanceTab).  Only '<' and '&' need
            %   escaping in this subset of HTML; '>' is left literal and is
            %   used as the tab > panel > field path separator.
            lines = { ...
                '<b>Tuning the AdamNLOpt solver</b>' ...
                '<br><br>' ...
                ['If a solve will not converge or is behaving badly, work through the steps below ' ...
                 'roughly in order &mdash; the earlier ones are the most common causes. Each step ' ...
                 'names the control to change and where to find it (Tab > Panel > Field). Hover any ' ...
                 'field for a full description, its recommended value, and its default. Clearing a ' ...
                 'text field restores that setting''s default.'] ...
                '<br><br>' ...
                '<ol>' ...
                ...
                ['<li><b>Rule out scaling first.</b> Poor scaling is the single most common cause ' ...
                 'of a "stuck" solve. Leave <i>Scaling &amp; Globalization > Automatic Scaling > ' ...
                 'Auto Scale Mode</i> at <i>Gradient Based</i> (the default). If a curvature-dominated ' ...
                 'objective is causing trouble, try <i>Curvature Based</i>. Only use <i>No Scaling</i> ' ...
                 'if you have already hand-normalized the problem.<br><br></li>'] ...
                ...
                ['<li><b>The solve errors out inside the solver</b> (e.g. "Matrix must have real ' ...
                 'diagonal"). Your objective or constraints are probably only valid inside the bounds, ' ...
                 'and a probe stepped outside the box. Turn ON <i>General > Finite Differences > Honor ' ...
                 'Bounds</i> so x0 and every finite-difference probe stay strictly within [lb, ub].' ...
                 '<br><br></li>'] ...
                ...
                ['<li><b>It stalls above the Optimality Tol, or the objective stops moving but it ' ...
                 'keeps iterating.</b> This usually means a noisy or simulation-based objective (ODE ' ...
                 'integration, iterative solvers). Turn ON <i>General > Finite Differences > ' ...
                 'Auto-Calibrate FD Step</i>; if it persists, set <i>FD Type</i> to central and loosen ' ...
                 '<i>General > Tolerances > Optimality Tol.</i> toward 1e-4. Do not set tolerances ' ...
                 'tighter than the accuracy your functions can actually deliver.<br><br></li>'] ...
                ...
                ['<li><b>It reports "local infeasibility", or feasibility blows up / diverges.</b> ' ...
                 'Keep the dual-step safeguards tight: <i>Duals &amp; Advanced > Dual Handling > Dual ' ...
                 'Step Max</i> and <i>Dual Fit Growth Max</i> should stay at 10, and <i>Scaling &amp; ' ...
                 'Globalization > Globalization > Kappa Theta Grow</i> at 100. For a run that genuinely ' ...
                 'runs away, arm the divergence detector by setting <i>Scaling &amp; Globalization > ' ...
                 'Divergence &amp; Result > Divergence Window</i> to a finite value such as 5.' ...
                 '<br><br></li>'] ...
                ...
                ['<li><b>The barrier looks frozen</b> (the mu parameter is stuck and the objective ' ...
                 'only crawls). This is almost always a symptom, not the cause &mdash; the automatic ' ...
                 'barrier-stall detector already handles the cases a lower barrier can fix, so forcing ' ...
                 'mu down (via <i>Barrier &amp; Trust Region</i>) tends to push the iterate off the ' ...
                 'central path and make things worse. Treat it as a conditioning/plateau problem ' ...
                 'instead, and see steps 3 and 7.<br><br></li>'] ...
                ...
                ['<li><b>A long solve stalls or regresses partway through.</b> Keep <i>Hessian &amp; ' ...
                 'Linear Algebra > Hessian Model > BFGS B0 Refresh</i> ON &mdash; on long runs the ' ...
                 'initial curvature scale goes stale and can stall (or fail) an otherwise healthy ' ...
                 'solve. For very large problems where a dense Hessian will not fit, switch ' ...
                 '<i>Hessian Approx.</i> to <i>Limited Memory BFGS</i>.<br><br></li>'] ...
                ...
                ['<li><b>It returns a worse point than one it clearly visited</b> (an oscillating ' ...
                 'endgame). The endpoint of a capped run is an arbitrary sample of a wandering ' ...
                 'sequence. Set <i>Scaling &amp; Globalization > Divergence &amp; Result > Return ' ...
                 'Iterate</i> to <i>bestKKT</i> so a limit exit hands back the best feasible, most ' ...
                 'stationary iterate it saw.<br><br></li>'] ...
                ...
                ['<li><b>It works but is too slow / expensive.</b> With an expensive objective and ' ...
                 'finite-difference derivatives, set <i>General > Parallelization > Parallel Mode</i> ' ...
                 'to <i>finitediff</i> so the probes run concurrently. Enable <i>Duals &amp; Advanced ' ...
                 '> Broyden Jacobian Updating > Enable Broyden Updates</i> to amortize an expensive ' ...
                 'constraint Jacobian (it can also auto-enable itself via <i>Cost Threshold</i>). Use ' ...
                 '<i>Limited Memory BFGS</i> for very large n.<br><br></li>'] ...
                ...
                ['<li><b>Still stuck &mdash; get more visibility.</b> Set <i>General > Diagnostics ' ...
                 '&amp; Display > Console Display</i> to <i>iter-debug</i> for extra columns, turn ON ' ...
                 '<i>Warn On Silent Failure</i> to surface conditions the solver normally absorbs, ' ...
                 'turn ON <i>Plot Solver Progress</i> to watch convergence live, and raise <i>Trace ' ...
                 'Level</i> to 2 for the costly conditioning probes.</li>'] ...
                ...
                '</ol>' ...
                };
            txt = strjoin(lines, '');
        end

        function d = getOptionDescriptions(~)
            %getOptionDescriptions Detailed help text per option (field name ==
            %   AdamNlOptOptions property name).  Each entry is a struct with:
            %     .desc - what the option does, and
            %     .use  - practical guidance on when to change it and what to
            %             set it to (may be '' when no extra guidance applies).
            %   applyTooltips assembles these, plus the default value, into the
            %   mouse-over tooltip for both the control and its label.  The
            %   content is drawn from the grouped rationale in
            %   adamnlopt.defaultOptions.
            mk = @(desc, use) struct('desc', desc, 'use', use);
            d = struct();

            % ---- Tolerances ----
            d.optTol = mk( ...
                'First-order optimality (stationarity / KKT) tolerance. The solve converges when the scaled first-order optimality residual falls to this value.', ...
                'Leave at 1e-6 for most problems. Loosen toward 1e-4 for noisy or simulation-based objectives that plateau above 1e-6; tighten to 1e-8 only when your derivatives are accurate to near machine precision. Tightening below your derivative accuracy just burns iterations.');
            d.feasTol = mk( ...
                'Primal feasibility tolerance: the largest allowed violation of the equality constraints, inequality constraints, and bounds at the solution.', ...
                'Match it to how tightly your constraints must actually hold. Loosen for noisy constraints; do not set it tighter than the accuracy to which your constraints can be evaluated.');
            d.compTol = mk( ...
                'Complementarity tolerance: how close each inactive multiplier x slack product must be to zero at the solution.', ...
                'Leave blank to tie it to the optimality tolerance (recommended). Set a number only if you need complementarity held to a different level than stationarity.');
            d.stepTol = mk( ...
                'Minimum step norm. Below this the solver treats the iterate as stalled and hands off to restoration / stall handling.', ...
                'Rarely changed. Raise it if the solver wastes iterations taking vanishingly small steps; lower it to let the solver keep pushing toward a hard-to-reach solution.');

            % ---- Objective plateau exit ----
            d.objPlateauWindow = mk( ...
                'Number of consecutive flat-objective iterations required before the plateau-based convergence exit fires. This is a secondary convergence signal for problems whose objective goes flat near the solution (e.g. free-final-time transcriptions) while the KKT residual keeps grinding down.', ...
                'Keep 40 for a good balance. Increase to be more conservative (fewer early exits). Set to Inf to disable the plateau exit entirely and converge only on the optimality tolerance.');
            d.objPlateauFtol = mk( ...
                'The "flat" threshold: a relative objective change |df|/max(1,|f|) at or below this counts the iteration as flat.', ...
                'Larger values call the objective flat more readily (earlier plateau exit); smaller values are stricter. 1e-5 is a sensible default.');
            d.objPlateauOptTol = mk( ...
                'A stationarity gate that must ALSO hold for the plateau exit to fire (default 3x the optimality tolerance).', ...
                'Keep it close to optTol. Too loose lets the solver exit above the true optimum -- measured: raising this to 1e-4 stopped ~1.5e-4 above the optimum on a test problem.');
            d.objPlateauOptWindow = mk( ...
                'Number of consecutive iterations the stationarity gate must be sustained before the plateau exit fires (1 = only touched once).', ...
                'Default 10 stops a single downward optimality spike from triggering a premature exit on an oscillating endgame. Raise it if you still see early exits on a wandering solve.');

            % ---- Finite differences ----
            d.finDiffType = mk( ...
                'Finite-difference scheme for gradients when no analytic derivative is supplied. Forward differences cost n evaluations; central differences cost 2n but are more accurate.', ...
                'Forward is fine for smooth objectives. Use central for noisy or strongly curved problems where forward gradients are too inaccurate. Overridden when Auto-Calibrate FD Step is on.');
            d.finDiffStepSize = mk( ...
                'Finite-difference step size used to probe gradients.', ...
                'The default sqrt(eps) assumes the objective is evaluated to machine precision. For simulation-based / noisy objectives it is far too small (differencing noise dominates) -- either turn on Auto-Calibrate FD Step (recommended) or set a step near the square root of your noise floor. Overridden when Auto-Calibrate is on.');
            d.autoFDStep = mk( ...
                'Calibrate the FD step size and type from an error V-curve measured at x0, overriding the two settings above.', ...
                'Leave ON for noisy / simulation-based objectives (ODE integration, iterative solvers) -- it finds the step that minimizes differencing error. Turn OFF only when you supply a hand-tuned step or need bit-for-bit reproducibility.');
            d.honorBounds = mk( ...
                'Keep x0 and every finite-difference / calibration probe strictly inside [lb, ub] (flipping forward differences to backward, or shrinking the step, near an active bound).', ...
                'Leave ON when the objective / constraints are only defined (or only real-valued) inside the box -- otherwise a probe can cross a bound and crash the solve. Turn OFF only for legacy bit-for-bit behaviour when the functions are defined everywhere.');

            % ---- Limits ----
            d.maxIter = mk( ...
                'Maximum number of solver iterations before a limit exit.', ...
                'Raise for hard problems that need more iterations to converge. 300 is enough for most well-scaled problems.');
            d.maxFunEvals = mk( ...
                'Maximum number of objective function evaluations before a limit exit.', ...
                'Raise if you hit this before converging, especially with finite-difference derivatives where each iteration costs many evaluations.');
            d.maxTime = mk( ...
                'Wall-clock time budget in seconds (Inf = no limit).', ...
                'Set a finite value to cap a long or expensive solve; on timeout the run returns its last (or best-KKT, per Return Iterate) point.');

            % ---- Diagnostics & display ----
            d.traceLevel = mk( ...
                'Per-iteration diagnostic trace detail: 0 = off, 1 = free quantities (essentially no cost), 2 = adds costly conditioning probes.', ...
                'Leave at 1 -- it records by-products the solver already computes. Use 2 only when actively debugging conditioning or convergence problems.');
            d.traceMaxRows = mk( ...
                'Preallocation hint for the diagnostic trace; it grows past this if the run is longer.', ...
                'Purely a performance hint. Raise it if you expect very long runs and want to avoid reallocation.');
            d.warnOnSilentFailure = mk( ...
                'Warn on conditions the solver normally absorbs silently: inertia-correction exhaustion, MINRES non-convergence, and BFGS flattening to a scaled identity.', ...
                'Turn ON when diagnosing a suspicious or non-converging solve. Leave OFF for production runs, as a long solve can emit many warnings.');
            d.plotSolverProgress = mk( ...
                'Show the built-in 2x2 live convergence plot (variables, constraints, objective, and closeness-to-convergence bars) during the solve.', ...
                'Handy for watching convergence interactively. Turn OFF for batch / headless runs or when the plotting overhead matters.');
            d.displayMode = mk( ...
                'Console output verbosity: off, iter (per-iteration table), iter-debug (adds diagnostic columns), or final (summary only).', ...
                'Use iter for normal work, iter-debug when debugging a non-converging solve, and off / final for batch runs. Display level never changes the solve itself.');
            d.logFile = mk( ...
                'Path to a file the iteration table and summary are appended to as the solve runs (flushed on every write). Blank disables file logging.', ...
                'Set it for long solves so an interrupted or errored run still leaves a usable log. Honoured only when Console Display is not "off".');

            % ---- Parallel ----
            d.parallel = mk( ...
                'Parallelization mode for evaluations: off, finitediff (run the finite-difference probes concurrently), or async.', ...
                'Use finitediff when derivatives are finite-differenced AND the objective is expensive, so the n / 2n probes run in parallel. Keep it off when the objective is cheap -- parallel overhead then dominates.');
            d.numWorkers = mk( ...
                'Number of parallel workers to request when a parallel mode is enabled.', ...
                'Set to the number of physical cores available; requesting more workers than cores rarely helps.');

            % ---- Hessian model ----
            d.hessianApprox = mk( ...
                'Model of the Hessian of the Lagrangian: exact (FD Hessian or your HessianFcn; quadratic convergence), bfgs (dense n-by-n secant, O(n^2)/iter), lbfgs (limited-memory, for large n), or fd.', ...
                'Keep dense BFGS whenever an n-by-n matrix fits -- the direct KKT solve already forms one, and dense BFGS accumulates curvature in every sampled direction. Switch to L-BFGS only when n is too large for a dense matrix. Use exact for small problems that need tight tolerances quickly.');
            d.bfgsGammaCurvCap = mk( ...
                'Ceiling on the one-shot initial BFGS scaling (B0), relative to the curvature of the first secant pair.', ...
                'Advanced / legacy lever -- prefer BFGS B0 Refresh, which fixes the same drift at its source. Only lower this (toward 1e2) if a solve diverges from an over-large initial curvature scale; too low (around 3) can diverge outright.');
            d.bfgsB0Refresh = mk( ...
                'Rebase the dense-BFGS scale onto a running median of the sampled curvature when it drifts (full BFGS only; L-BFGS already refreshes its scale every update).', ...
                'Leave ON -- on long solves the one-shot initial scale becomes stale and stalls (or fails) convergence, and the refresh walks it back to the true curvature at no wall-clock cost. Turn OFF only to recover pre-2026 behaviour if a regression correlates with a nonzero rebase count.');
            d.bfgsB0RefreshWindow = mk( ...
                'Number of recent curvature pairs in the rolling geometric median used to decide a B0 refresh.', ...
                'Advanced tuning; the default of 8 is well-behaved.');
            d.bfgsB0RefreshFactor = mk( ...
                'Drift ratio from the live scale that triggers a B0 refresh (a refresh fires when the median curvature differs from the current scale by more than this factor).', ...
                'Advanced tuning. Lower it for more frequent refreshes, raise it to refresh only on large drift.');
            d.bfgsB0RefreshRefractory = mk( ...
                'Minimum number of curvature pairs between two consecutive B0 refreshes.', ...
                'Advanced tuning; prevents the refresh from thrashing. Default 5.');
            d.bfgsB0RefreshMaxDrop = mk( ...
                'Largest single-refresh reduction allowed in the B0 scale.', ...
                'Advanced tuning. Bounds how soft a single rebase can make the model (too soft a B0 gives too long a step). Default 100.');
            d.bfgsB0RefreshMinLearned = mk( ...
                'Block a refresh once this fraction of n curvature pairs has been learned since the last one -- protecting a model that is already working.', ...
                'Advanced tuning. On small problems a rebase discards useful curvature, so the default 0.20 blocks it once enough has been learned; on large problems it is effectively inert.');
            d.bfgsResetMaxDrop = mk( ...
                'Cap on the scale reduction during a BFGS conditioning-fault reset (Inf = unbounded, the legacy behaviour).', ...
                'Default Inf reproduces historical behaviour. Set 100 (mirroring the B0 refresh cap) if a solve takes wild, over-long steps immediately after a BFGS reset.');
            d.bfgsCondMax = mk( ...
                'Condition-number ceiling that triggers a BFGS fault reset. At the default 1e12 it effectively never fires -- resets come from loss of positive definiteness instead.', ...
                'Advanced. Do NOT lower this alone; an early reset still takes one unfiltered curvature scale, so it is only useful paired with a finite BFGS Reset Max Drop.');
            d.lbfgsMemory = mk( ...
                'Number of stored curvature pairs for limited-memory BFGS (ignored by dense BFGS).', ...
                'Only relevant when Hessian Approx. is L-BFGS. More pairs give a better curvature model at higher cost per iteration.');

            % ---- Linear algebra ----
            d.linearSolver = mk( ...
                'How the Newton-KKT system is solved: direct (LDL'' factorization; robust), krylov (matrix-free iterative; for very large / sparse systems), or auto (switch by problem size).', ...
                'Keep direct unless the problem is too large to factorize. Use auto to let the solver pick based on size.');
            d.krylovMethod = mk( ...
                'Iterative method for Krylov KKT solves: MINRES (symmetric indefinite) or GMRES.', ...
                'Only relevant when the linear solver is Krylov (or auto has switched to it). MINRES is the default for the symmetric KKT system.');
            d.krylovAutoDim = mk( ...
                'In "auto" linear-solver mode, switch to Krylov once n + mE (variables plus equalities) exceeds this size.', ...
                'Raise it if direct factorization is still fast at your problem size; lower it to go matrix-free sooner. Only affects "auto" mode.');
            d.krylovMaxIter = mk( ...
                'Maximum Krylov iterations per KKT solve. Leave blank for a problem-size default.', ...
                'Only relevant for Krylov solves. Set a number only if you need to bound the cost of each iterative solve.');
            d.forcingEtaMax = mk( ...
                'Upper clamp on the inexact-Newton forcing sequence -- the loosest relative accuracy allowed for a Krylov KKT solve.', ...
                'Advanced Krylov tuning. Only relevant for Krylov solves.');
            d.forcingEtaMin = mk( ...
                'Lower clamp on the inexact-Newton forcing sequence -- the tightest relative accuracy demanded of a Krylov KKT solve.', ...
                'Advanced Krylov tuning. Only relevant for Krylov solves.');
            d.forcingGamma = mk( ...
                'Eisenstat-Walker choice-2 coefficient governing how the Krylov solve accuracy tightens as the solver converges.', ...
                'Advanced Krylov tuning. Only relevant for Krylov solves.');
            d.forcingAlpha = mk( ...
                'Eisenstat-Walker choice-2 exponent governing how the Krylov solve accuracy tightens as the solver converges.', ...
                'Advanced Krylov tuning. Only relevant for Krylov solves.');
            d.precondition = mk( ...
                'Preconditioner for Krylov KKT solves: none or jacobi.', ...
                'Jacobi usually accelerates convergence at negligible cost. Only relevant for Krylov solves.');

            % ---- Scaling ----
            d.autoScale = mk( ...
                'Automatic internal problem scaling applied at x0: gradient (variable + Jacobian-row scaling), curvature (adds an objective-curvature scale), bounds (variable scaling only), or none.', ...
                'Poor scaling is the single most common cause of a "stuck" solve, so leave auto-scaling ON. Use curvature if a curvature-dominated objective causes dual-step trouble. Use none only to reproduce legacy behaviour or when your problem is already carefully normalized.');
            d.autoScaleMaxSpread = mk( ...
                'Largest permitted spread max(Dx)/min(Dx) in the variable scaling (Inf = uncapped). Capping it bounds the conditioning damage the scaling can induce to spread^2.', ...
                'Keep 1e4 (bounds induced conditioning at 1e8, still safely within double precision). Lower it if scaling seems to hurt on a box spanning many orders of magnitude; Inf restores the raw bound-range rule.');
            d.autoScaleCurvGate = mk( ...
                'Per-constraint cap on the scaled objective curvature in "curvature" mode (Inf disables the objective leg, making curvature identical to gradient).', ...
                'Advanced. Only relevant in curvature scaling mode; the default keeps well-scaled problems bit-identical to gradient mode.');
            d.autoScaleCurvProbeMaxDim = mk( ...
                'Largest problem size n for which "curvature" mode runs its curvature probe (which costs 2n extra objective evaluations at x0).', ...
                'Above this size, curvature mode degrades gracefully to gradient mode. Raise it only if the probe cost is acceptable at larger n.');

            % ---- Divergence & result ----
            d.divergeFactor = mk( ...
                'Feasibility worse than this factor times the best-ever feasibility counts the iteration as "regressed" for the divergence detector.', ...
                'Part of the (off-by-default) blow-up detector; only takes effect when Divergence Window is finite. Kept deliberately loose so a normal recovery does not trip it.');
            d.divergeWindow = mk( ...
                'Consecutive regressed iterations before the run is declared diverged and rolled back to its best iterate (Inf = detector off).', ...
                'DISABLED by default because it false-positives on healthy endgame wobble. Set a finite value (e.g. 5) only to auto-abort a run you specifically expect to run away.');
            d.returnIterate = mk( ...
                'Which iterate a limit exit (max iterations / evals / time) returns: last (the point the loop ended on) or bestKKT (the best feasible, most-stationary iterate seen).', ...
                'Use bestKKT on an oscillating run, where the endpoint of a capped solve is an arbitrary sample of a wandering sequence. Use last when you want the exact state after N iterations, e.g. for a warm-start continuation. Convergence and divergence exits ignore this setting.');

            % ---- Globalization ----
            d.globalization = mk( ...
                'Line-search step-acceptance strategy: filter (accept when feasibility OR objective improves) or merit (a single combined merit function).', ...
                'Filter is usually the more robust choice. Try merit if the filter behaves poorly on your particular problem.');
            d.kappaThetaGrow = mk( ...
                'Veto a line-search trial whose constraint violation exceeds this factor times max(theta0, feasTol) (Inf disables the veto). A blow-up guard, not a feasibility policy.', ...
                'Leave at 100 (deliberately loose). It stops a single step from raising feasibility violation by orders of magnitude while never vetoing the modest theta increases a healthy solve routinely takes.');
            d.useSOC = mk( ...
                'Enable second-order correction in the filter line search, which counters the Maratos effect (full steps rejected because constraint curvature raises the violation) on strongly nonlinear constraints.', ...
                'Leave ON -- it lets the solver take full, fast steps near the solution on curved constraints.');
            d.socMax = mk( ...
                'Maximum successive second-order-correction re-solves per iteration.', ...
                'More re-solves allow harder corrections at added cost per iteration. Default 4.');
            d.socThreshold = mk( ...
                'Trigger a second-order correction when the accepted line-search step falls below this fraction of the maximum step.', ...
                'Advanced tuning of when SOC kicks in. Default 0.1.');

            % ---- Barrier ----
            d.mu0 = mk( ...
                'Initial barrier (central-path) parameter for the interior-point method.', ...
                'Larger gives a more conservative, more interior start (safer but slower); smaller is more aggressive. Rarely needs changing.');
            d.muMin = mk( ...
                'Minimum barrier parameter. Blank ties it to the optimality tolerance (0.1 x optTol).', ...
                'Leave blank (recommended). Set a number only if you need the barrier driven lower or held higher than the optimality tolerance implies.');
            d.muGamma = mk( ...
                'Linear barrier reduction factor: the multiplicative shrink applied to mu on an ordinary reduction (default 0.2 = a 5x drop).', ...
                'Smaller shrinks the barrier faster (more aggressive central-path march). Rarely changed.');
            d.muBeta = mk( ...
                'Superlinear barrier exponent: near the solution mu is reduced as mu^(1+beta).', ...
                'Controls how sharply the barrier accelerates downward in the endgame. Rarely changed.');
            d.kappaMu = mk( ...
                'Reduce mu once the mu-perturbed KKT error falls within this factor times mu.', ...
                'Historically raised to unfreeze a stalled barrier, but the automatic barrier-stall detector (see Barrier Stall Factor) now handles that, so this rarely needs changing.');
            d.tau = mk( ...
                'Fraction-to-boundary base that keeps steps strictly interior (a step may close at most a fraction tau of the distance to a bound).', ...
                'Closer to 1 allows longer steps toward the bounds (faster but riskier near the boundary). Rarely changed from 0.995.');
            d.barrierStallFactor = mk( ...
                'Cap on the automatic kappaMu widening the solver uses to break a barrier stall (when complementarity and feasibility are satisfied but the stationarity block is not).', ...
                'Keep it modest -- it is NOT free headroom. Too large collapses the barrier prematurely and strands the solve above the optimum; 10 is the largest cap that does not regress the standard test set.');
            d.feasAdmitFactor = mk( ...
                'Feasibility floor (as a multiple of feasTol) for admitting a mu-curable structural stall to the barrier-stall detector, so the admission test stops chasing mu downward.', ...
                'Advanced. The default 100 matches the threshold the mode controller uses to call feasibility "under control".');

            % ---- Trust region ----
            d.delta0 = mk( ...
                'Initial trust-region radius.', ...
                'Smaller gives more cautious first steps. Only relevant when the normal/tangential trust-region path (Normal/Tangential Decomp.) is active.');
            d.deltaMax = mk( ...
                'Maximum trust-region radius.', ...
                'Only relevant on the trust-region path. Rarely changed.');
            d.trEta1 = mk( ...
                'Accept a trust-region step when the actual/predicted reduction ratio exceeds this.', ...
                'Advanced trust-region tuning. Only relevant on the trust-region path.');
            d.trEta2 = mk( ...
                'Expand the trust-region radius when the actual/predicted reduction ratio exceeds this (on a boundary step).', ...
                'Advanced trust-region tuning. Only relevant on the trust-region path.');
            d.trShrink = mk( ...
                'Radius shrink factor applied on a rejected trust-region step.', ...
                'Advanced trust-region tuning. Only relevant on the trust-region path.');
            d.trExpand = mk( ...
                'Radius growth factor applied on a very good trust-region step.', ...
                'Advanced trust-region tuning. Only relevant on the trust-region path.');
            d.trMaxInner = mk( ...
                'Maximum trust-region inner iterations before the solver falls back to a line search.', ...
                'Only relevant when Normal/Tangential Decomp. is on. Default 20.');

            % ---- Adaptive mode & restoration ----
            d.modeSwitch = mk( ...
                'Enable Level-1 adaptive mode control -- the solver switches strategy (interior-point / equality / feasibility) based on the local situation.', ...
                'Leave ON; it helps the solver adapt to changing conditions during a solve.');
            d.modeSwitchStagnWindow = mk( ...
                'Number of consecutive iterations used to detect constraint-violation stagnation for the mode controller.', ...
                'Advanced tuning; only meaningful when Adaptive Mode Switch is on. Default 5.');
            d.enableRestoration = mk( ...
                'Enable the feasibility restoration phase, which recovers the iterate when a step collapses on an infeasible point.', ...
                'Leave ON for constrained problems; it rescues stalled infeasible iterates rather than failing outright.');
            d.restStallWindow = mk( ...
                'Consecutive feasibility-stall iterations before a collapsed line search is allowed to trigger restoration or a local-infeasibility exit.', ...
                'Advanced tuning; only meaningful when restoration is enabled. Default 5.');
            d.modeNearBdryAugJE = mk( ...
                'In near-boundary mode, promote high-confidence active inequalities to equalities.', ...
                'Advanced; only meaningful with Adaptive Mode Switch on. Leave off unless you specifically want this behaviour.');
            d.useNTdecomp = mk( ...
                'Use a normal/tangential step decomposition with a trust-region inner loop instead of the default KKT solve + line search.', ...
                'Experimental alternative step strategy. Try it only if the default KKT + line-search path struggles on your problem.');

            % ---- Dual (Lagrange multiplier) handling ----
            d.dualStepMax = mk( ...
                'Cap on the equality-multiplier step ||dlamE|| per step, relative to max(1, ||lamE||) -- a dual trust region (Inf disables it).', ...
                'Load-bearing safeguard on stiff multiple-shooting / adjoint problems, where the reduced dual step can blow up along a near-singular direction. Keep it tight (10); loosening lets the multipliers random-walk upward and the optimality residual spike.');
            d.dualCondMax = mk( ...
                'Target ceiling on the reduced dual-system (Schur complement) condition number after scale-aware regularization (Inf disables it).', ...
                'Keeps the factorization numerically honest on near-singular dual systems and is inert on well-conditioned ones. Rarely changed from 1e8.');
            d.dualCondProbeMaxDim = mk( ...
                'Skip the Schur conditioning probe (cost O(mE^2 x n)) when the equality count mE exceeds this; dual regularization then falls back to the pivot gate.', ...
                'Advanced cost control. Raise it if you want the probe active on larger equality systems.');
            d.lsMultiplierRefresh = mk( ...
                'Re-estimate the equality multipliers each iteration by least squares (dominance-gated), correcting costates that lag the moving primal iterate.', ...
                'Leave ON when the equality Jacobian is full row rank -- it stabilizes costate-lag stalls cheaply. Turn OFF for ill-conditioned equality Jacobians where the fit is unreliable.');
            d.lsRefreshDomRatio = mk( ...
                'Fire the multiplier refresh only when optimality exceeds this factor times feasibility -- i.e. when a costate-lag stall (not a feasibility drive) is holding up the KKT residual.', ...
                'Advanced tuning; scale-relative, so no absolute tolerance is involved. Default 10.');
            d.lsRefreshFeasTol = mk( ...
                'Legacy absolute feasibility gate for the multiplier refresh; no longer the primary trigger (the dominance ratio above is).', ...
                'Rarely changed. Kept for backward compatibility.');
            d.lsRefreshDeadband = mk( ...
                'Adopt a re-fitted set of multipliers only when it beats the current weighted dual infeasibility by at least this factor (< 1).', ...
                'Prevents noise-level toggling of the multipliers when the refresh fires every iteration in the endgame. Default 0.9.');
            d.dualFitCondMax = mk( ...
                'Truncate costate-fit singular directions below sigma_max/this to drop the near-null tail that only inflates ||lamE|| (Inf disables truncation).', ...
                'Set it just above your healthy cond(JE) so the true range survives and the ill-conditioned tail is cut. Protects only large equality systems (see Dual Fit Min Eqs.).');
            d.dualFitCondMinEq = mk( ...
                'Minimum number of equalities before the truncated costate fit is used; below it, a plain minimum-norm fit is used instead.', ...
                'Advanced. The truncation protects a near-null tail, which only a large equality system can have. Default 8.');
            d.dualFitGrowthMax = mk( ...
                'Reject a multiplier refresh that would grow ||lamE|| beyond this factor times its previous value -- an adoption backstop against runaway costates.', ...
                'Keep it tight (10): the blow-up compounds across steps, so a loose factor lets the costates ratchet up until they poison the Hessian secant. 10 admits legitimate endgame growth while biting at the first toxic step.');
            d.activeBoundGapTol = mk( ...
                'A variable within this relative gap of a bound is treated as "pinned" / active (0 disables active-bound row exclusion entirely).', ...
                'Keep it nonzero on bang-bang / bang-off optimal-control problems where a variable sits on a bound: it stops the lagging bound multiplier from corrupting the costate fit and the reported optimality metric. Inert on interior / unconstrained problems.');
            d.excludeActiveBoundRows = mk( ...
                'Drop pinned-variable (active-bound) rows from the costate least-squares fit and the optimality / stationarity metric.', ...
                'Leave ON; it is inert on any variable not at a bound, so interior / unconstrained problems are untouched, and it prevents a false stationarity gap at a genuine active-bound solution.');

            % ---- Degeneracy ----
            d.enableDegeneracyDetection = mk( ...
                'Run degeneracy detection each iteration to identify redundant / dependent constraints.', ...
                'Enable if you suspect linearly dependent constraints causing rank problems. It adds per-iteration cost, so leave off otherwise.');

            % ---- Broyden Jacobian updating ----
            d.enableBroyden = mk( ...
                'Use Broyden rank-1 Jacobian updates between exact refreshes, amortizing the cost of an expensive constraint Jacobian across iterations.', ...
                'Enable when the constraint Jacobian is expensive to finite-difference. It can also auto-enable itself via Cost Threshold below.');
            d.broydenMaxStale = mk( ...
                'Number of steps before a mandatory exact Jacobian refresh when Broyden updating is active.', ...
                'Lower for more accuracy (more frequent exact Jacobians), higher for more speed. Default 20.');
            d.broydenTol = mk( ...
                'Broyden model-error tolerance that triggers an early exact Jacobian refresh before the max-stale limit.', ...
                'Advanced tuning; only relevant when Broyden updating is active. Default 0.1.');
            d.costThreshold = mk( ...
                'Average finite-difference Jacobian time (seconds) above which Broyden updating is auto-enabled.', ...
                'Leave at the default to let the solver switch Broyden on automatically for expensive problems; raise it to require a more expensive Jacobian before it kicks in.');
        end
    end
end
