classdef AdamNlOptOptions < matlab.mixin.SetGet
    %AdamNlOptOptions Options for the AdamNLOpt nonlinear programming solver.
    %   Full mirror of adamnlopt.defaultOptions(), less the fields that
    %   AdamNlOptOptimizer sets programmatically (the gradient/Hessian
    %   specification fields and the plot/iteration callbacks).
    %
    %   Numeric properties use the same NaN sentinel as FminconOptions: a NaN
    %   means "leave whatever adamnlopt.defaultOptions() put there".  That
    %   matters for compTol, muMin and krylovMaxIter, whose default of [] is
    %   meaningful -- the solver ties them to optTol/problem size internally --
    %   and must not be clobbered with a number.  Inf is a real value for
    %   maxTime, divergeWindow and bfgsResetMaxDrop; only NaN suppresses.

    properties
        %Tolerances
        optTol(1,1) double = 1E-6;
        feasTol(1,1) double = 1E-6;
        compTol(1,1) double = NaN;  %NaN -> tied to optTol by the solver
        stepTol(1,1) double = 1E-12;

        %Limits
        maxIter(1,1) double = 300;
        maxFunEvals(1,1) double = 100000;
        maxTime(1,1) double = Inf;  %seconds; enforced by AdamNlOptOptimizer, not the solver

        %Objective plateau exit
        objPlateauWindow(1,1) double = 40;
        objPlateauFtol(1,1) double = 1E-5;
        objPlateauOptTol(1,1) double = 3E-6;
        objPlateauOptWindow(1,1) double = 10;

        %Derivatives / finite differences
        finDiffStepSize(1,1) double = sqrt(eps);
        finDiffType(1,1) FminconFiniteDiffTypeEnum = FminconFiniteDiffTypeEnum.TwoPtForwardDiff;
        autoFDStep(1,1) logical = true;
        honorBounds(1,1) logical = true;

        %Hessian model
        hessianApprox(1,1) AdamNlOptHessianApproxEnum = AdamNlOptHessianApproxEnum.BFGS;
        bfgsGammaCurvCap(1,1) double = 1E4;
        bfgsB0Refresh(1,1) logical = true;
        bfgsB0RefreshWindow(1,1) double = 8;
        bfgsB0RefreshFactor(1,1) double = 3;
        bfgsB0RefreshRefractory(1,1) double = 5;
        bfgsB0RefreshMaxDrop(1,1) double = 100;
        bfgsB0RefreshMinLearned(1,1) double = 0.2;
        bfgsResetMaxDrop(1,1) double = Inf;
        bfgsCondMax(1,1) double = 1E12;
        lbfgsMemory(1,1) double = 10;

        %Linear algebra
        linearSolver(1,1) AdamNlOptLinearSolverEnum = AdamNlOptLinearSolverEnum.Direct;
        krylovMethod(1,1) AdamNlOptKrylovMethodEnum = AdamNlOptKrylovMethodEnum.MinRes;
        krylovAutoDim(1,1) double = 500;
        krylovMaxIter(1,1) double = NaN;  %NaN -> sized from the problem by the solver
        forcingEtaMax(1,1) double = 0.9;
        forcingEtaMin(1,1) double = 1E-8;
        forcingGamma(1,1) double = 1;
        forcingAlpha(1,1) double = 1.618;
        precondition(1,1) AdamNlOptPrecondEnum = AdamNlOptPrecondEnum.Jacobi;

        %Scaling
        autoScale(1,1) AdamNlOptAutoScaleEnum = AdamNlOptAutoScaleEnum.Gradient;
        autoScaleMaxSpread(1,1) double = 1E4;
        autoScaleCurvGate(1,1) double = 1E4;
        autoScaleCurvProbeMaxDim(1,1) double = 400;

        %Globalization
        globalization(1,1) AdamNlOptGlobalizationEnum = AdamNlOptGlobalizationEnum.Filter;
        kappaThetaGrow(1,1) double = 100;
        useSOC(1,1) logical = true;
        socMax(1,1) double = 4;
        socThreshold(1,1) double = 0.1;

        %Divergence detection / result selection
        divergeFactor(1,1) double = 1000;
        divergeWindow(1,1) double = Inf;
        returnIterate(1,1) AdamNlOptReturnIterateEnum = AdamNlOptReturnIterateEnum.Last;

        %Barrier and trust region
        mu0(1,1) double = 0.1;
        muMin(1,1) double = NaN;  %NaN -> tied to optTol by the solver
        muGamma(1,1) double = 0.2;
        muBeta(1,1) double = 1.5;
        kappaMu(1,1) double = 10;
        tau(1,1) double = 0.995;
        delta0(1,1) double = 1;
        deltaMax(1,1) double = 1E6;
        trEta1(1,1) double = 0.1;
        trEta2(1,1) double = 0.75;
        trShrink(1,1) double = 0.25;
        trExpand(1,1) double = 2;
        trMaxInner(1,1) double = 20;
        barrierStallFactor(1,1) double = 10;
        feasAdmitFactor(1,1) double = 100;

        %Adaptive mode control / feasibility restoration
        modeSwitch(1,1) logical = true;
        modeSwitchStagnWindow(1,1) double = 5;
        enableRestoration(1,1) logical = true;
        restStallWindow(1,1) double = 5;
        modeNearBdryAugJE(1,1) logical = false;
        useNTdecomp(1,1) logical = false;

        %Dual (Lagrange multiplier) handling
        dualStepMax(1,1) double = 10;
        dualCondMax(1,1) double = 1E8;
        dualCondProbeMaxDim(1,1) double = 400;
        lsMultiplierRefresh(1,1) logical = true;
        lsRefreshDomRatio(1,1) double = 10;
        lsRefreshFeasTol(1,1) double = 1E-3;
        lsRefreshDeadband(1,1) double = 0.9;
        dualFitCondMax(1,1) double = 1E4;
        dualFitCondMinEq(1,1) double = 8;
        dualFitGrowthMax(1,1) double = 10;
        activeBoundGapTol(1,1) double = 1E-3;
        excludeActiveBoundRows(1,1) logical = true;

        %Degeneracy
        enableDegeneracyDetection(1,1) logical = false;

        %Broyden Jacobian updating
        enableBroyden(1,1) logical = false;
        broydenMaxStale(1,1) double = 20;
        broydenTol(1,1) double = 0.1;
        costThreshold(1,1) double = 0.1;

        %Diagnostics and display
        traceLevel(1,1) double = 1;
        traceMaxRows(1,1) double = 20000;
        warnOnSilentFailure(1,1) logical = false;
        plotSolverProgress(1,1) logical = false;
        displayMode(1,1) AdamNlOptDisplayEnum = AdamNlOptDisplayEnum.Iterative;
        logFile(1,:) char = '';

        %Parallel
        parallel(1,1) AdamNlOptParallelEnum = AdamNlOptParallelEnum.DoNotUseParallel;
        numWorkers(1,1) double = feature('numCores');
    end

    methods
        function options = getOptionsForOptimizer(obj, ~)
            %getOptionsForOptimizer Build the adamnlopt options struct.
            %   The second argument (typical X) is accepted to match the
            %   AbstractOptimizerOptions signature; adamnlopt has no TypicalX
            %   equivalent -- it does its own automatic scaling instead.

            options = adamnlopt.defaultOptions();

            %Numeric options: {property name, adamnlopt field name}.  NaN
            %valued properties are left at the solver's default.
            numericMap = { ...
                'optTol',                   'optTol'; ...
                'feasTol',                  'feasTol'; ...
                'compTol',                  'compTol'; ...
                'stepTol',                  'stepTol'; ...
                'maxIter',                  'maxIter'; ...
                'maxFunEvals',              'maxFunEvals'; ...
                'maxTime',                  'maxTime'; ...
                'objPlateauWindow',         'objPlateauWindow'; ...
                'objPlateauFtol',           'objPlateauFtol'; ...
                'objPlateauOptTol',         'objPlateauOptTol'; ...
                'objPlateauOptWindow',      'objPlateauOptWindow'; ...
                'finDiffStepSize',          'FiniteDifferenceStepSize'; ...
                'bfgsGammaCurvCap',         'bfgsGammaCurvCap'; ...
                'bfgsB0RefreshWindow',      'bfgsB0RefreshWindow'; ...
                'bfgsB0RefreshFactor',      'bfgsB0RefreshFactor'; ...
                'bfgsB0RefreshRefractory',  'bfgsB0RefreshRefractory'; ...
                'bfgsB0RefreshMaxDrop',     'bfgsB0RefreshMaxDrop'; ...
                'bfgsB0RefreshMinLearned',  'bfgsB0RefreshMinLearned'; ...
                'bfgsResetMaxDrop',         'bfgsResetMaxDrop'; ...
                'bfgsCondMax',              'bfgsCondMax'; ...
                'lbfgsMemory',              'lbfgsMemory'; ...
                'krylovAutoDim',            'krylovAutoDim'; ...
                'krylovMaxIter',            'krylovMaxIter'; ...
                'forcingEtaMax',            'forcingEtaMax'; ...
                'forcingEtaMin',            'forcingEtaMin'; ...
                'forcingGamma',             'forcingGamma'; ...
                'forcingAlpha',             'forcingAlpha'; ...
                'autoScaleMaxSpread',       'autoScaleMaxSpread'; ...
                'autoScaleCurvGate',        'autoScaleCurvGate'; ...
                'autoScaleCurvProbeMaxDim', 'autoScaleCurvProbeMaxDim'; ...
                'kappaThetaGrow',           'kappaThetaGrow'; ...
                'socMax',                   'socMax'; ...
                'socThreshold',             'socThreshold'; ...
                'divergeFactor',            'divergeFactor'; ...
                'divergeWindow',            'divergeWindow'; ...
                'mu0',                      'mu0'; ...
                'muMin',                    'muMin'; ...
                'muGamma',                  'muGamma'; ...
                'muBeta',                   'muBeta'; ...
                'kappaMu',                  'kappaMu'; ...
                'tau',                      'tau'; ...
                'delta0',                   'delta0'; ...
                'deltaMax',                 'deltaMax'; ...
                'trEta1',                   'trEta1'; ...
                'trEta2',                   'trEta2'; ...
                'trShrink',                 'trShrink'; ...
                'trExpand',                 'trExpand'; ...
                'trMaxInner',               'trMaxInner'; ...
                'barrierStallFactor',       'barrierStallFactor'; ...
                'feasAdmitFactor',          'feasAdmitFactor'; ...
                'modeSwitchStagnWindow',    'modeSwitchStagnWindow'; ...
                'restStallWindow',          'restStallWindow'; ...
                'dualStepMax',              'dualStepMax'; ...
                'dualCondMax',              'dualCondMax'; ...
                'dualCondProbeMaxDim',      'dualCondProbeMaxDim'; ...
                'lsRefreshDomRatio',        'lsRefreshDomRatio'; ...
                'lsRefreshFeasTol',         'lsRefreshFeasTol'; ...
                'lsRefreshDeadband',        'lsRefreshDeadband'; ...
                'dualFitCondMax',           'dualFitCondMax'; ...
                'dualFitCondMinEq',         'dualFitCondMinEq'; ...
                'dualFitGrowthMax',         'dualFitGrowthMax'; ...
                'activeBoundGapTol',        'activeBoundGapTol'; ...
                'broydenMaxStale',          'broydenMaxStale'; ...
                'broydenTol',               'broydenTol'; ...
                'costThreshold',            'costThreshold'; ...
                'traceLevel',               'traceLevel'; ...
                'traceMaxRows',             'traceMaxRows'; ...
                };

            for(i=1:size(numericMap,1))
                value = obj.(numericMap{i,1});

                if(not(isnan(value)))
                    options = AdamNlOptOptions.setOptField(options, numericMap{i,2}, value);
                end
            end

            %Logical options.
            logicalMap = { ...
                'autoFDStep',                'autoFDStep'; ...
                'honorBounds',               'HonorBounds'; ...
                'bfgsB0Refresh',             'bfgsB0Refresh'; ...
                'useSOC',                    'useSOC'; ...
                'modeSwitch',                'modeSwitch'; ...
                'enableRestoration',         'enableRestoration'; ...
                'modeNearBdryAugJE',         'modeNearBdryAugJE'; ...
                'useNTdecomp',               'useNTdecomp'; ...
                'lsMultiplierRefresh',       'lsMultiplierRefresh'; ...
                'excludeActiveBoundRows',    'excludeActiveBoundRows'; ...
                'enableDegeneracyDetection', 'enableDegeneracyDetection'; ...
                'enableBroyden',             'enableBroyden'; ...
                'warnOnSilentFailure',       'warnOnSilentFailure'; ...
                'plotSolverProgress',        'Plot'; ...
                };

            for(i=1:size(logicalMap,1))
                options = AdamNlOptOptions.setOptField(options, logicalMap{i,2}, obj.(logicalMap{i,1}));
            end

            %Enumeration backed options: the enum's optionStr is the string
            %adamnlopt expects.
            enumMap = { ...
                'finDiffType',    'FiniteDifferenceType'; ...
                'hessianApprox',  'hessianApprox'; ...
                'linearSolver',   'linearSolver'; ...
                'krylovMethod',   'krylovMethod'; ...
                'precondition',   'precondition'; ...
                'autoScale',      'autoScale'; ...
                'globalization',  'globalization'; ...
                'returnIterate',  'returnIterate'; ...
                'displayMode',    'Display'; ...
                'parallel',       'parallel'; ...
                };

            for(i=1:size(enumMap,1))
                enumObj = obj.(enumMap{i,1});
                options = AdamNlOptOptions.setOptField(options, enumMap{i,2}, enumObj.optionStr);
            end

            %Log file: empty means "no log", which is the solver default.
            if(not(isempty(obj.logFile)))
                options = AdamNlOptOptions.setOptField(options, 'LogFile', obj.logFile);
            end
        end

        function tf = usesParallel(obj)
            tf = obj.parallel.optionVal;
        end

        function numWorkers = getNumParaWorkers(obj)
            numWorkers = obj.numWorkers;
        end
    end

    methods(Static)
        function obj = loadobj(obj)
            if(obj.numWorkers < 1 || obj.numWorkers > feature('numCores'))
                obj.numWorkers = feature('numCores');
            end
        end
    end

    methods(Static, Access=private)
        function options = setOptField(options, fieldName, value)
            %setOptField Assign an adamnlopt option, erroring on an unknown
            %name.  adamnlopt only *warns* about unrecognized options and then
            %ignores them, so a typo here would otherwise fail silently.

            if(not(isfield(options, fieldName)))
                error('AdamNlOptOptions:unknownOption', ...
                      'Unknown adamnlopt option name: %s', fieldName);
            end

            options.(fieldName) = value;
        end
    end
end
