function orbitDecay = getDefaultOrbitDecay()
    orbitDecay = struct('use',false, ...
                        'scArea', 0, ...
                        'solarFlux', 120, ...
                        'geoMagInd', 7);
end